### ISSUE TITLE
Update user name and email into .git/config

### ISSUE THREAD

**Issue by tsq** [pretty-girl/client-react-native#2]
<img width="536" alt="09d35d45-9df9-4c35-a98f-ccab5ac3325d" src="https://cloud.githubusercontent.com/assets/6081537/11918019/49a7cac4-a75a-11e5-875e-123f9776d2ed.png">

Hi @Ovaldi! Your commit info about the author is missing. You should update you git config in `.git/config` file  and add `user` config as below 

```
[user]
   name = Ovaldi
   email = your email
```

**Comment by Ovaldi** [comment]
haha, got it
